#-----------------------------------------------------------------------------#
#   Quarter Bot - A Twitter bot that flips a coin.                            #
#   emoji.py                                                                  #
#                                                                             #
#   Copyright (c) 2014, Seventy Four, Inc.                                    #
#                                                                             #
#   This program is free software: you can redistribute it and/or modify      #
#   it under the terms of the GNU General Public License as published by      #
#   the Free Software Foundation, either version 3 of the License, or         #
#   (at your option) any later version.                                       #
#                                                                             #
#   This program is distributed in the hope that it will be useful,           #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of            #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
#   GNU General Public License for more details.                              #
#                                                                             #
#   You should have received a copy of the GNU General Public License         #
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.     #
#-----------------------------------------------------------------------------#



# See: http://www.unicode.org/charts/PDF/Unicode-7.0/U70-1F300.pdf

EMOJI = {
    # Weather, landscape, and sky symbols:
    'CYCLONE':                                                  u'\U0001F300',
    'FOGGY':                                                    u'\U0001F301',
    'CLOSED UMBRELLA':                                          u'\U0001F302',
    'NIGHT WITH STARS':                                         u'\U0001F303',
    'SUNRISE OVER MOUNTAINS':                                   u'\U0001F304',
    'SUNRISE':                                                  u'\U0001F305',
    'CITYSCAPE AT DUSK':                                        u'\U0001F306',
    'SUNSET OVER BUILDINGS':                                    u'\U0001F307',
    'RAINBOW':                                                  u'\U0001F308',
    'BRIDGE AT NIGHT':                                          u'\U0001F309',
    'WATER WAVE':                                               u'\U0001F30A',
    'VOLCANO':                                                  u'\U0001F30B',
    'MILKY WAY':                                                u'\U0001F30C',

    # Globe symbols:
    'EARTH GLOBE EUROPE-AFRICA':                                u'\U0001F30D',
    'EARTH GLOBE AMERICAS':                                     u'\U0001F30E',
    'EARTH GLOBE ASIA-AUSTRALIA':                               u'\U0001F30F',
    'GLOBE WITH MERIDIANS':                                     u'\U0001F310',

    # Moon, sun, and star symbols:
    'NEW MOON SYMBOL':                                          u'\U0001F311',
    'WAXING CRESCENT MOON SYMBOL':                              u'\U0001F312',
    'FIRST QUARTER MOON SYMBOL':                                u'\U0001F313',
    'WAXING GIBBOUS MOON SYMBOL':                               u'\U0001F314',
    'FULL MOON SYMBOL':                                         u'\U0001F315',
    'WANING GIBBOUS MOON SYMBOL':                               u'\U0001F316',
    'LAST QUARTER MOON SYMBOL':                                 u'\U0001F317',
    'WANING CRESCENT MOON SYMBOL':                              u'\U0001F318',
    'CRESCENT MOON':                                            u'\U0001F319',
    'NEW MOON WITH FACE':                                       u'\U0001F31A',
    'FIRST QUARTER MOON WITH FACE':                             u'\U0001F31B',
    'LAST QUARTER MOON WITH FACE':                              u'\U0001F31C',
    'FULL MOON WITH FACE':                                      u'\U0001F31D',
    'SUN WITH FACE':                                            u'\U0001F31E',
    'GLOWING STAR':                                             u'\U0001F31F',
    'SHOOTING STAR':                                            u'\U0001F320',

    # Weather symbols:
    # 'THERMOMETER':                                              u'\U0001F321',
    # 'BLACK DROPLET':                                            u'\U0001F322',
    # 'WHITE SUN':                                                u'\U0001F323',
    # 'WHITE SUN WITH SMALL CLOUD':                               u'\U0001F324',
    # 'WHITE SUN BEHIND CLOUD':                                   u'\U0001F325',
    # 'WHITE SUN BEHIND CLOUD WITH RAIN':                         u'\U0001F326',
    # 'CLOUD WITH RAIN':                                          u'\U0001F327',
    # 'CLOUD WITH SNOW':                                          u'\U0001F328',
    # 'CLOUD WITH LIGHTNING':                                     u'\U0001F329',
    # 'CLOUD WITH TORNADO':                                       u'\U0001F32A',
    # 'FOG':                                                      u'\U0001F32B',
    # 'WIND BLOWING FACE':                                        u'\U0001F32C',

    # Plant symbols:
    'CHESTNUT':                                                 u'\U0001F330',
    'SEEDLING':                                                 u'\U0001F331',
    'EVERGREEN TREE':                                           u'\U0001F332',
    'DECIDUOUS TREE':                                           u'\U0001F333',
    'PALM TREE':                                                u'\U0001F334',
    'CACTUS':                                                   u'\U0001F335',
    # 'HOT PEPPER ':                                              u'\U0001F336',
    'TULIP':                                                    u'\U0001F337',
    'CHERRY BLOSSOM':                                           u'\U0001F338',
    'ROSE':                                                     u'\U0001F339',
    'HIBISCUS':                                                 u'\U0001F33A',
    'SUNFLOWER':                                                u'\U0001F33B',
    'BLOSSOM':                                                  u'\U0001F33C',
    'EAR OF MAIZE':                                             u'\U0001F33D',
    'EAR OF RICE':                                              u'\U0001F33E',
    'HERB':                                                     u'\U0001F33F',
    'FOUR LEAF CLOVER':                                         u'\U0001F340',
    'MAPLE LEAF':                                               u'\U0001F341',
    'FALLEN LEAF':                                              u'\U0001F342',
    'LEAF FLUTTERING IN WIND':                                  u'\U0001F343',
    'MUSHROOM':                                                 u'\U0001F344',

    # Fruit and vegetable symbols:
    'TOMATO':                                                   u'\U0001F345',
    'AUBERGINE':                                                u'\U0001F346',
    'GRAPES':                                                   u'\U0001F347',
    'MELON':                                                    u'\U0001F348',
    'WATERMELON':                                               u'\U0001F349',
    'TANGERINE':                                                u'\U0001F34A',
    'LEMON':                                                    u'\U0001F34B',
    'BANANA':                                                   u'\U0001F34C',
    'PINEAPPLE':                                                u'\U0001F34D',
    'RED APPLE':                                                u'\U0001F34E',
    'GREEN APPLE':                                              u'\U0001F34F',
    'PEAR':                                                     u'\U0001F350',
    'PEACH':                                                    u'\U0001F351',
    'CHERRIES':                                                 u'\U0001F352',
    'STRAWBERRY':                                               u'\U0001F353',

    # Food symbols:
    'HAMBURGER':                                                u'\U0001F354',
    'SLICE OF PIZZA':                                           u'\U0001F355',
    'MEAT ON BONE':                                             u'\U0001F356',
    'POULTRY LEG':                                              u'\U0001F357',
    'RICE CRACKER':                                             u'\U0001F358',
    'RICE BALL':                                                u'\U0001F359',
    'COOKED RICE':                                              u'\U0001F35A',
    'CURRY AND RICE':                                           u'\U0001F35B',
    'STEAMING BOWL':                                            u'\U0001F35C',
    'SPAGHETTI':                                                u'\U0001F35D',
    'BREAD':                                                    u'\U0001F35E',
    'FRENCH FRIES':                                             u'\U0001F35F',
    'ROASTED SWEET POTATO':                                     u'\U0001F360',
    'DANGO':                                                    u'\U0001F361',
    'ODEN':                                                     u'\U0001F362',
    'SUSHI':                                                    u'\U0001F363',
    'FRIED SHRIMP':                                             u'\U0001F364',
    'FISH CAKE WITH SWIRL DESIGN':                              u'\U0001F365',
    'SOFT ICE CREAM':                                           u'\U0001F366',
    'SHAVED ICE':                                               u'\U0001F367',
    'ICE CREAM':                                                u'\U0001F368',
    'DOUGHNUT':                                                 u'\U0001F369',
    'COOKIE':                                                   u'\U0001F36A',
    'CHOCOLATE BAR':                                            u'\U0001F36B',
    'CANDY':                                                    u'\U0001F36C',
    'LOLLIPOP':                                                 u'\U0001F36D',
    'CUSTARD':                                                  u'\U0001F36E',
    'HONEY POT':                                                u'\U0001F36F',
    'SHORTCAKE':                                                u'\U0001F370',
    'BENTO BOX':                                                u'\U0001F371',
    'POT OF FOOD':                                              u'\U0001F372',
    'COOKING':                                                  u'\U0001F373',
    'FORK AND KNIFE':                                           u'\U0001F374',

    # Beverage symbols:
    'TEACUP WITHOUT HANDLE':                                    u'\U0001F375',
    'SAKE BOTTLE AND CUP':                                      u'\U0001F376',
    'WINE GLASS':                                               u'\U0001F377',
    'COCKTAIL GLASS':                                           u'\U0001F378',
    'TROPICAL DRINK':                                           u'\U0001F379',
    'BEER MUG':                                                 u'\U0001F37A',
    'CLINKING BEER MUGS':                                       u'\U0001F37B',
    'BABY BOTTLE':                                              u'\U0001F37C',

    # Accommodation symbol:
    # 'FORK AND KNIFE WITH PLATE':                                u'\U0001F37D',

    # Celebration symbols:
    'RIBBON':                                                   u'\U0001F380',
    'WRAPPED PRESENT':                                          u'\U0001F381',
    'BIRTHDAY CAKE':                                            u'\U0001F382',
    'JACK-O-LANTERN':                                           u'\U0001F383',
    'CHRISTMAS TREE':                                           u'\U0001F384',
    'FATHER CHRISTMAS':                                         u'\U0001F385',
    'FIREWORKS':                                                u'\U0001F386',
    'FIREWORK SPARKLER':                                        u'\U0001F387',
    'BALLOON':                                                  u'\U0001F388',
    'PARTY POPPER':                                             u'\U0001F389',
    'CONFETTI BALL':                                            u'\U0001F38A',
    'TANABATA TREE':                                            u'\U0001F38B',
    'CROSSED FLAGS':                                            u'\U0001F38C',
    'PINE DECORATION':                                          u'\U0001F38D',
    'JAPANESE DOLLS':                                           u'\U0001F38E',
    'CARP STREAMER':                                            u'\U0001F38F',
    'WIND CHIME':                                               u'\U0001F390',
    'MOON VIEWING CEREMONY':                                    u'\U0001F391',
    'SCHOOL SATCHEL':                                           u'\U0001F392',
    'GRADUATION CAP':                                           u'\U0001F393',
    # 'HEART WITH TIP ON THE LEFT':                               u'\U0001F394',
    # 'BOUQUET OF FLOWERS':                                       u'\U0001F395',
    # 'MILITARY MEDAL':                                           u'\U0001F396',
    # 'REMINDER RIBBON':                                          u'\U0001F397',

    # Musical symbols:
    # 'MUSICAL KEYBOARD WITH JACKS':                              u'\U0001F398',
    # 'STUDIO MICROPHONE':                                        u'\U0001F399',
    # 'LEVEL SLIDER':                                             u'\U0001F39A',
    # 'CONTROL KNOBS':                                            u'\U0001F39B',
    # 'BEAMED ASCENDING MUSICAL NOTES':                           u'\U0001F39C',
    # 'BEAMED DESCENDING MUSICAL NOTES':                          u'\U0001F39D',

    # Entertainment symbols:
    # 'FILM FRAMES':                                              u'\U0001F39E',
    # 'ADMISSION TICKETS':                                        u'\U0001F39F',
    'CAROUSEL HORSE':                                           u'\U0001F3A0',
    'FERRIS WHEEL':                                             u'\U0001F3A1',
    'ROLLER COASTER':                                           u'\U0001F3A2',
    'FISHING POLE AND FISH':                                    u'\U0001F3A3',
    'MICROPHONE':                                               u'\U0001F3A4',
    'MOVIE CAMERA':                                             u'\U0001F3A5',
    'CINEMA':                                                   u'\U0001F3A6',
    'HEADPHONE':                                                u'\U0001F3A7',
    'ARTIST PALETTE':                                           u'\U0001F3A8',
    'TOP HAT':                                                  u'\U0001F3A9',
    'CIRCUS TENT':                                              u'\U0001F3AA',
    'TICKET':                                                   u'\U0001F3AB',
    'CLAPPER BOARD':                                            u'\U0001F3AC',
    'PERFORMING ARTS':                                          u'\U0001F3AD',

    # Game symbols:
    'VIDEO GAME':                                               u'\U0001F3AE',
    'DIRECT HIT':                                               u'\U0001F3AF',
    'SLOT MACHINE':                                             u'\U0001F3B0',
    'BILLIARDS':                                                u'\U0001F3B1',
    'GAME DIE':                                                 u'\U0001F3B2',
    'BOWLING':                                                  u'\U0001F3B3',
    'FLOWER PLAYING CARDS':                                     u'\U0001F3B4',

    # Musical symbols:
    'MUSICAL NOTE':                                             u'\U0001F3B5',
    'MULTIPLE MUSICAL NOTES':                                   u'\U0001F3B6',
    'SAXOPHONE':                                                u'\U0001F3B7',
    'GUITAR':                                                   u'\U0001F3B8',
    'MUSICAL KEYBOARD':                                         u'\U0001F3B9',
    'TRUMPET':                                                  u'\U0001F3BA',
    'VIOLIN':                                                   u'\U0001F3BB',
    'MUSICAL SCORE':                                            u'\U0001F3BC',

    # Sport symbols:
    'RUNNING SHIRT WITH SASH':                                  u'\U0001F3BD',
    'TENNIS RACQUET AND BALL':                                  u'\U0001F3BE',
    'SKI AND SKI BOOT':                                         u'\U0001F3BF',
    'BASKETBALL AND HOOP':                                      u'\U0001F3C0',
    'CHEQUERED FLAG':                                           u'\U0001F3C1',
    'SNOWBOARDER':                                              u'\U0001F3C2',
    'RUNNER':                                                   u'\U0001F3C3',
    'SURFER':                                                   u'\U0001F3C4',
    # 'SPORTS MEDAL':                                             u'\U0001F3C5',
    'TROPHY':                                                   u'\U0001F3C6',
    'HORSE RACING':                                             u'\U0001F3C7',
    'AMERICAN FOOTBALL':                                        u'\U0001F3C8',
    'RUGBY FOOTBALL':                                           u'\U0001F3C9',
    'SWIMMER':                                                  u'\U0001F3CA',
    # 'WEIGHT LIFTER':                                            u'\U0001F3CB',
    # 'GOLFER':                                                   u'\U0001F3CC',
    # 'RACING MOTORCYCLE':                                        u'\U0001F3CD',
    # 'RACING CAR':                                               u'\U0001F3CE',

    # Buiding and map symbols:
    # 'SNOW CAPPED MOUNTAIN':                                     u'\U0001F3D4',
    # 'CAMPING':                                                  u'\U0001F3D5',
    # 'BEACH WITH UMBRELLA':                                      u'\U0001F3D6',
    # 'BUILDING CONSTRUCTION':                                    u'\U0001F3D7',
    # 'HOUSE BUILDINGS':                                          u'\U0001F3D8',
    # 'CITYSCAPE':                                                u'\U0001F3D9',
    # 'DERELICT HOUSE BUILDING':                                  u'\U0001F3DA',
    # 'CLASSICAL BUILDING':                                       u'\U0001F3DB',
    # 'DESERT':                                                   u'\U0001F3DC',
    # 'DESERT ISLAND':                                            u'\U0001F3DD',
    # 'NATIONAL PARK':                                            u'\U0001F3DE',
    # 'STADIUM':                                                  u'\U0001F3DF',
    'HOUSE BUILDING':                                           u'\U0001F3E0',
    'HOUSE WITH GARDEN':                                        u'\U0001F3E1',
    'OFFICE BUILDING':                                          u'\U0001F3E2',
    'JAPANESE POST OFFICE':                                     u'\U0001F3E3',
    'EUROPEAN POST OFFICE':                                     u'\U0001F3E4',
    'HOSPITAL':                                                 u'\U0001F3E5',
    'BANK':                                                     u'\U0001F3E6',
    'AUTOMATED TELLER MACHINE':                                 u'\U0001F3E7',
    'HOTEL':                                                    u'\U0001F3E8',
    'LOVE HOTEL':                                               u'\U0001F3E9',
    'CONVENIENCE STORE':                                        u'\U0001F3EA',
    'SCHOOL':                                                   u'\U0001F3EB',
    'DEPARTMENT STORE':                                         u'\U0001F3EC',
    'FACTORY':                                                  u'\U0001F3ED',
    'IZAKAYA LANTERN':                                          u'\U0001F3EE',
    'JAPANESE CASTLE':                                          u'\U0001F3EF',
    'EUROPEAN CASTLE':                                          u'\U0001F3F0',

    # Flag symbols:
    # 'WHITE PENNANT':                                            u'\U0001F3F1',
    # 'BLACK PENNANT':                                            u'\U0001F3F2',
    # 'WAVING WHITE FLAG':                                        u'\U0001F3F3',
    # 'WAVING BLACK FLAG':                                        u'\U0001F3F4',

    # Rosettes:
    # 'ROSETTE':                                                  u'\U0001F3F5',
    # 'BLACK ROSETTE':                                            u'\U0001F3F6',

    # Miscellaneous symbol:
    # 'LABEL':                                                    u'\U0001F3F7',

    # Animal symbols:
    'RAT':                                                      u'\U0001F400',
    'MOUSE':                                                    u'\U0001F401',
    'OX':                                                       u'\U0001F402',
    'WATER BUFFALO':                                            u'\U0001F403',
    'COW':                                                      u'\U0001F404',
    'TIGER':                                                    u'\U0001F405',
    'LEOPARD':                                                  u'\U0001F406',
    'RABBIT':                                                   u'\U0001F407',
    'CAT':                                                      u'\U0001F408',
    'DRAGON':                                                   u'\U0001F409',
    'CROCODILE':                                                u'\U0001F40A',
    'WHALE':                                                    u'\U0001F40B',
    'SNAIL':                                                    u'\U0001F40C',
    'SNAKE':                                                    u'\U0001F40D',
    'HORSE':                                                    u'\U0001F40E',
    'RAM':                                                      u'\U0001F40F',
    'GOAT':                                                     u'\U0001F410',
    'SHEEP':                                                    u'\U0001F411',
    'MONKEY':                                                   u'\U0001F412',
    'ROOSTER':                                                  u'\U0001F413',
    'CHICKEN':                                                  u'\U0001F414',
    'DOG':                                                      u'\U0001F415',
    'PIG':                                                      u'\U0001F416',
    'BOAR':                                                     u'\U0001F417',
    'ELEPHANT':                                                 u'\U0001F418',
    'OCTOPUS':                                                  u'\U0001F419',
    'SPIRAL SHELL':                                             u'\U0001F41A',
    'BUG':                                                      u'\U0001F41B',
    'ANT':                                                      u'\U0001F41C',
    'HONEYBEE':                                                 u'\U0001F41D',
    'LADY BEETLE':                                              u'\U0001F41E',
    'FISH':                                                     u'\U0001F41F',
    'TROPICAL FISH':                                            u'\U0001F420',
    'BLOWFISH':                                                 u'\U0001F421',
    'TURTLE':                                                   u'\U0001F422',
    'HATCHING CHICK':                                           u'\U0001F423',
    'BABY CHICK':                                               u'\U0001F424',
    'FRONT-FACING BABY CHICK':                                  u'\U0001F425',
    'BIRD':                                                     u'\U0001F426',
    'PENGUIN':                                                  u'\U0001F427',
    'KOALA':                                                    u'\U0001F428',
    'POODLE':                                                   u'\U0001F429',
    'DROMEDARY CAMEL':                                          u'\U0001F42A',
    'BACTRIAN CAMEL':                                           u'\U0001F42B',
    'DOLPHIN':                                                  u'\U0001F42C',

    # Animal faces:
    'MOUSE FACE':                                               u'\U0001F42D',
    'COW FACE':                                                 u'\U0001F42E',
    'TIGER FACE':                                               u'\U0001F42F',
    'RABBIT FACE':                                              u'\U0001F430',
    'CAT FACE':                                                 u'\U0001F431',
    'DRAGON FACE':                                              u'\U0001F432',
    'SPOUTING WHALE':                                           u'\U0001F433',
    'HORSE FACE':                                               u'\U0001F434',
    'MONKEY FACE':                                              u'\U0001F435',
    'DOG FACE':                                                 u'\U0001F436',
    'PIG FACE':                                                 u'\U0001F437',
    'FROG FACE':                                                u'\U0001F438',
    'HAMSTER FACE':                                             u'\U0001F439',
    'WOLF FACE':                                                u'\U0001F43A',
    'BEAR FACE':                                                u'\U0001F43B',
    'PANDA FACE':                                               u'\U0001F43C',
    'PIG NOSE':                                                 u'\U0001F43D',

    # Animal symbols:
    'PAW PRINTS':                                               u'\U0001F43E',
    # 'CHIPMUNK':                                                 u'\U0001F43F',

    # Facial parts symbols:
    'EYES':                                                     u'\U0001F440',
    # 'EYE':                                                      u'\U0001F441',
    'EAR':                                                      u'\U0001F442',
    'NOSE':                                                     u'\U0001F443',
    'MOUTH':                                                    u'\U0001F444',
    'TONGUE':                                                   u'\U0001F445',

    # Hand symbols:
    'WHITE UP POINTING BACKHAND INDEX':                         u'\U0001F446',
    'WHITE DOWN POINTING BACKHAND INDEX':                       u'\U0001F447',
    'WHITE LEFT POINTING BACKHAND INDEX':                       u'\U0001F448',
    'WHITE RIGHT POINTING BACKHAND INDEX':                      u'\U0001F449',
    'FISTED HAND SIGN':                                         u'\U0001F44A',
    'WAVING HAND SIGN':                                         u'\U0001F44B',
    'OK HAND SIGN':                                             u'\U0001F44C',
    'THUMBS UP SIGN':                                           u'\U0001F44D',
    'THUMBS DOWN SIGN':                                         u'\U0001F44E',
    'CLAPPING HANDS SIGN':                                      u'\U0001F44F',
    'OPEN HANDS SIGN':                                          u'\U0001F450',

    # Clothing and accessories:
    'CROWN':                                                    u'\U0001F451',
    'WOMANS HAT':                                               u'\U0001F452',
    'EYEGLASSES':                                               u'\U0001F453',
    'NECKTIE':                                                  u'\U0001F454',
    'T-SHIRT':                                                  u'\U0001F455',
    'JEANS':                                                    u'\U0001F456',
    'DRESS':                                                    u'\U0001F457',
    'KIMONO':                                                   u'\U0001F458',
    'BIKINI':                                                   u'\U0001F459',
    'WOMANS CLOTHES':                                           u'\U0001F45A',
    'PURSE':                                                    u'\U0001F45B',
    'HANDBAG':                                                  u'\U0001F45C',
    'POUCH':                                                    u'\U0001F45D',
    'MANS SHOE':                                                u'\U0001F45E',
    'ATHLETIC SHOE':                                            u'\U0001F45F',
    'HIGH-HEELED SHOE':                                         u'\U0001F460',
    'WOMANS SANDAL':                                            u'\U0001F461',
    'WOMANS BOOTS':                                             u'\U0001F462',
    'FOOTPRINTS':                                               u'\U0001F463',

    # Portrait and role symbols:
    'BUST IN SILHOUETTE':                                       u'\U0001F464',
    'BUSTS IN SILHOUETTE':                                      u'\U0001F465',
    'BOY':                                                      u'\U0001F466',
    'GIRL':                                                     u'\U0001F467',
    'MAN':                                                      u'\U0001F468',
    'WOMAN':                                                    u'\U0001F469',
    'FAMILY':                                                   u'\U0001F46A',
    'MAN AND WOMAN HOLDING HANDS':                              u'\U0001F46B',
    'TWO MEN HOLDING HANDS':                                    u'\U0001F46C',
    'TWO WOMEN HOLDING HANDS':                                  u'\U0001F46D',
    'POLICE OFFICER':                                           u'\U0001F46E',
    'WOMAN WITH BUNNY EARS':                                    u'\U0001F46F',
    'BRIDE WITH VEIL':                                          u'\U0001F470',
    'PERSON WITH BLOND HAIR':                                   u'\U0001F471',
    'MAN WITH GUA PI MAO':                                      u'\U0001F472',
    'MAN WITH TURBAN':                                          u'\U0001F473',
    'OLDER MAN':                                                u'\U0001F474',
    'OLDER WOMAN':                                              u'\U0001F475',
    'BABY':                                                     u'\U0001F476',
    'CONSTRUCTION WORKER':                                      u'\U0001F477',

    # Fairy tale symbols:
    'PRINCESS':                                                 u'\U0001F478',
    'JAPANESE OGRE':                                            u'\U0001F479',
    'JAPANESE GOBLIN':                                          u'\U0001F47A',
    'GHOST':                                                    u'\U0001F47B',
    'BABY ANGEL':                                               u'\U0001F47C',
    'EXTRATERRESTRIAL ALIEN':                                   u'\U0001F47D',
    'ALIEN MONSTER':                                            u'\U0001F47E',
    'IMP':                                                      u'\U0001F47F',
    'SKULL':                                                    u'\U0001F480',

    # Role symbols:
    'INFORMATION DESK PERSON':                                  u'\U0001F481',
    'GUARDSMAN':                                                u'\U0001F482',
    'DANCER':                                                   u'\U0001F483',

    # Personal care symbols:
    'LIPSTICK':                                                 u'\U0001F484',
    'NAIL POLISH':                                              u'\U0001F485',
    'FACE MASSAGE':                                             u'\U0001F486',
    'HAIRCUT':                                                  u'\U0001F487',
    'BARBER POLE':                                              u'\U0001F488',

    # Medical symbols:
    'SYRINGE':                                                  u'\U0001F489',
    'PILL':                                                     u'\U0001F48A',

    # Romance symbols:
    'KISS MARK':                                                u'\U0001F48B',
    'LOVE LETTER':                                              u'\U0001F48C',
    'RING':                                                     u'\U0001F48D',
    'GEM STONE':                                                u'\U0001F48E',
    'KISS':                                                     u'\U0001F48F',
    'BOUQUET':                                                  u'\U0001F490',
    'COUPLE WITH HEART':                                        u'\U0001F491',
    'WEDDING':                                                  u'\U0001F492',

    # Heart symbols:
    'BEATING HEART':                                            u'\U0001F493',
    'BROKEN HEART':                                             u'\U0001F494',
    'TWO HEARTS':                                               u'\U0001F495',
    'SPARKLING HEART':                                          u'\U0001F496',
    'GROWING HEART':                                            u'\U0001F497',
    'HEART WITH ARROW':                                         u'\U0001F498',
    'BLUE HEART':                                               u'\U0001F499',
    'GREEN HEART':                                              u'\U0001F49A',
    'YELLOW HEART':                                             u'\U0001F49B',
    'PURPLE HEART':                                             u'\U0001F49C',
    'HEART WITH RIBBON':                                        u'\U0001F49D',
    'REVOLVING HEARTS':                                         u'\U0001F49E',
    'HEART DECORATION':                                         u'\U0001F49F',

    # Comic style symbols:
    'DIAMOND SHAPE WITH A DOT INSIDE':                          u'\U0001F4A0',
    'ELECTRIC LIGHT BULB':                                      u'\U0001F4A1',
    'ANGER SYMBOL':                                             u'\U0001F4A2',
    'BOMB':                                                     u'\U0001F4A3',
    'SLEEPING SYMBOL':                                          u'\U0001F4A4',
    'COLLISION SYMBOL':                                         u'\U0001F4A5',
    'SPLASHING SWEAT SYMBOL':                                   u'\U0001F4A6',
    'DROPLET':                                                  u'\U0001F4A7',
    'DASH SYMBOL':                                              u'\U0001F4A8',
    'PILE OF POO':                                              u'\U0001F4A9',
    'FLEXED BICEPS':                                            u'\U0001F4AA',
    'DIZZY SYMBOL':                                             u'\U0001F4AB',
    'SPEECH BALLOON':                                           u'\U0001F4AC',
    'THOUGHT BALLOON':                                          u'\U0001F4AD',

    # Japanese school grade symbols:
    'WHITE FLOWER':                                             u'\U0001F4AE',
    'HUNDRED POINTS SYMBOL':                                    u'\U0001F4AF',

    # Money symbols:
    'MONEY BAG':                                                u'\U0001F4B0',
    'CURRENCY EXCHANGE':                                        u'\U0001F4B1',
    'HEAVY DOLLAR SIGN':                                        u'\U0001F4B2',
    'CREDIT CARD':                                              u'\U0001F4B3',
    'BANKNOTE WITH YEN SIGN':                                   u'\U0001F4B4',
    'BANKNOTE WITH DOLLAR SIGN':                                u'\U0001F4B5',
    'BANKNOTE WITH EURO SIGN':                                  u'\U0001F4B6',
    'BANKNOTE WITH POUND SIGN':                                 u'\U0001F4B7',
    'MONEY WITH WINGS':                                         u'\U0001F4B8',
    'CHART WITH UPWARDS TREND AND YEN SIGN':                    u'\U0001F4B9',

    # Office symbols:
    'SEAT':                                                     u'\U0001F4BA',
    'PERSONAL COMPUTER':                                        u'\U0001F4BB',
    'BRIEFCASE':                                                u'\U0001F4BC',
    'MINIDISC':                                                 u'\U0001F4BD',
    'FLOPPY DISK':                                              u'\U0001F4BE',
    'OPTICAL DISC':                                             u'\U0001F4BF',
    'DVD':                                                      u'\U0001F4C0',
    'FILE FOLDER':                                              u'\U0001F4C1',
    'OPEN FILE FOLDER':                                         u'\U0001F4C2',
    'PAGE WITH CURL':                                           u'\U0001F4C3',
    'PAGE FACING UP':                                           u'\U0001F4C4',
    'CALENDAR':                                                 u'\U0001F4C5',
    'TEAR-OFF CALENDAR':                                        u'\U0001F4C6',
    'CARD INDEX':                                               u'\U0001F4C7',
    'CHART WITH UPWARDS TREND':                                 u'\U0001F4C8',
    'CHART WITH DOWNWARDS TREND':                               u'\U0001F4C9',
    'BAR CHART':                                                u'\U0001F4CA',
    'CLIPBOARD':                                                u'\U0001F4CB',
    'PUSHPIN':                                                  u'\U0001F4CC',
    'ROUND PUSHPIN':                                            u'\U0001F4CD',
    'PAPERCLIP':                                                u'\U0001F4CE',
    'STRAIGHT RULER':                                           u'\U0001F4CF',
    'TRIANGULAR RULER':                                         u'\U0001F4D0',
    'BOOKMARK TABS':                                            u'\U0001F4D1',
    'LEDGER':                                                   u'\U0001F4D2',
    'NOTEBOOK':                                                 u'\U0001F4D3',
    'NOTEBOOK WITH DECORATIVE COVER':                           u'\U0001F4D4',
    'CLOSED BOOK':                                              u'\U0001F4D5',
    'OPEN BOOK':                                                u'\U0001F4D6',
    'GREEN BOOK':                                               u'\U0001F4D7',
    'BLUE BOOK':                                                u'\U0001F4D8',
    'ORANGE BOOK':                                              u'\U0001F4D9',
    'BOOKS':                                                    u'\U0001F4DA',
    'NAME BADGE':                                               u'\U0001F4DB',
    'SCROLL':                                                   u'\U0001F4DC',

    # Communication symbols:
    'MEMO':                                                     u'\U0001F4DD',
    'TELEPHONE RECEIVER':                                       u'\U0001F4DE',
    'PAGER':                                                    u'\U0001F4DF',
    'FAX MACHINE':                                              u'\U0001F4E0',
    'SATELLITE ANTENNA':                                        u'\U0001F4E1',
    'PUBLIC ADDRESS LOUDSPEAKER':                               u'\U0001F4E2',
    'CHEERING MEGAPHONE':                                       u'\U0001F4E3',
    'OUTBOX TRAY':                                              u'\U0001F4E4',
    'INBOX TRAY':                                               u'\U0001F4E5',
    'PACKAGE':                                                  u'\U0001F4E6',
    'E-MAIL SYMBOL':                                            u'\U0001F4E7',
    'INCOMING ENVELOPE':                                        u'\U0001F4E8',
    'ENVELOPE WITH DOWNWARDS ARROW ABOVE':                      u'\U0001F4E9',
    'CLOSED MAILBOX WITH LOWERED FLAG':                         u'\U0001F4EA',
    'CLOSED MAILBOX WITH RAISED FLAG':                          u'\U0001F4EB',
    'OPEN MAILBOX WITH RAISED FLAG':                            u'\U0001F4EC',
    'OPEN MAILBOX WITH LOWERED FLAG':                           u'\U0001F4ED',
    'POSTBOX':                                                  u'\U0001F4EE',
    'POSTAL HORN':                                              u'\U0001F4EF',
    'NEWSPAPER':                                                u'\U0001F4F0',
    'MOBILE PHONE':                                             u'\U0001F4F1',
    'MOBILE PHONE WITH RIGHTWARDS ARROW AT LEFT':               u'\U0001F4F2',
    'VIBRATION MODE':                                           u'\U0001F4F3',
    'MOBILE PHONE OFF':                                         u'\U0001F4F4',
    'NO MOBILE PHONES':                                         u'\U0001F4F5',
    'ANTENNA WITH BARS':                                        u'\U0001F4F6',

    # Audio and video symbols:
    'CAMERA':                                                   u'\U0001F4F7',
    # 'CAMERA WITH FLASH':                                        u'\U0001F4F8',
    'VIDEO CAMERA':                                             u'\U0001F4F9',
    'TELEVISION':                                               u'\U0001F4FA',
    'RADIO':                                                    u'\U0001F4FB',
    'VIDEOCASSETTE':                                            u'\U0001F4FC',
    # 'FILM PROJECTOR':                                           u'\U0001F4FD',
    # 'PORTABLE STEREO':                                          u'\U0001F4FE',

    # User interface symbols:
    'TWISTED RIGHTWARDS ARROWS':                                u'\U0001F500',
    'CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS':    u'\U0001F501',
    'CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS WITH CIRCLED ONE OVERLAY':       u'\U0001F502',
    'CLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS':       u'\U0001F503',
    'ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS':   u'\U0001F504',
    'LOW BRIGHTNESS SYMBOL':                                    u'\U0001F505',
    'HIGH BRIGHTNESS SYMBOL':                                   u'\U0001F506',
    'SPEAKER WITH CANCELLATION STROKE':                         u'\U0001F507',
    'SPEAKER':                                                  u'\U0001F508',
    'SPEAKER WITH ONE SOUND WAVE':                              u'\U0001F509',
    'SPEAKER WITH THREE SOUND WAVES':                           u'\U0001F50A',
    'BATTERY':                                                  u'\U0001F50A',
    'ELECTRIC PLUG':                                            u'\U0001F50C',
    'LEFT-POINTING MAGNIFYING GLASS':                           u'\U0001F50D',
    'RIGHT-POINTING MAGNIFYING GLASS':                          u'\U0001F50E',
    'LOCK WITH INK PEN':                                        u'\U0001F50F',
    'CLOSED LOCK WITH KEY':                                     u'\U0001F510',
    'KEY':                                                      u'\U0001F511',
    'LOCK':                                                     u'\U0001F512',
    'OPEN LOCK':                                                u'\U0001F513',
    'BELL':                                                     u'\U0001F514',
    'BELL WITH CANCELLATION STROKE':                            u'\U0001F515',
    'BOOKMARK':                                                 u'\U0001F516',
    'LINK SYMBOL':                                              u'\U0001F517',
    'RADIO BUTTON':                                             u'\U0001F518',

    # Words with arrows:
    'BACK WITH LEFTWARDS ARROW ABOVE':                          u'\U0001F519',
    'END WITH LEFTWARDS ARROW ABOVE':                           u'\U0001F51A',
    'ON WITH EXCLAMATION MARK WITH LEFT RIGHT ARROW ABOVE':     u'\U0001F51B',
    'SOON WITH RIGHTWARDS ARROW ABOVE':                         u'\U0001F51C',
    'TOP WITH UPWARDS ARROW ABOVE':                             u'\U0001F51D',

    # Enclosed alphanumeric symbols:
    'NO ONE UNDER EIGHTEEN SYMBOL':                             u'\U0001F51E',
    'KEYCAP TEN':                                               u'\U0001F51F',

    # User interface input status symbols:
    'INPUT SYMBOL FOR LATIN CAPITAL LETTERS':                   u'\U0001F520',
    'INPUT SYMBOL FOR LATIN SMALL LETTERS':                     u'\U0001F521',
    'INPUT SYMBOL FOR NUMBERS':                                 u'\U0001F522',
    'INPUT SYMBOL FOR SYMBOLS':                                 u'\U0001F523',
    'INPUT SYMBOL FOR LATIN LETTERS':                           u'\U0001F524',

    # Tool symbols:
    'FIRE':                                                     u'\U0001F525',
    'ELECTRIC TORCH':                                           u'\U0001F526',
    'WRENCH':                                                   u'\U0001F527',
    'HAMMER':                                                   u'\U0001F528',
    'NUT AND BOLT':                                             u'\U0001F529',
    'HOCHO':                                                    u'\U0001F52A',
    'PISTOL':                                                   u'\U0001F52B',
    'MICROSCOPE':                                               u'\U0001F52C',
    'TELESCOPE':                                                u'\U0001F52D',
    'CRYSTAL BALL':                                             u'\U0001F52E',
    'SIX POINTED STAR WITH MIDDLE DOT':                         u'\U0001F52F',
    'JAPANESE SYMBOL FOR BEGINNER':                             u'\U0001F530',
    'TRIDENT EMBLEM':                                           u'\U0001F531',

    # Geometric shapes:
    'BLACK SQUARE BUTTON':                                      u'\U0001F532',
    'WHITE SQUARE BUTTON':                                      u'\U0001F533',
    'LARGE RED CIRCLE':                                         u'\U0001F534',
    'LARGE BLUE CIRCLE':                                        u'\U0001F535',
    'LARGE ORANGE DIAMOND':                                     u'\U0001F536',
    'LARGE BLUE DIAMOND':                                       u'\U0001F537',
    'SMALL ORANGE DIAMOND':                                     u'\U0001F538',
    'SMALL BLUE DIAMOND':                                       u'\U0001F539',

    # User interface symbols:
    'UP-POINTING RED TRIANGLE':                                 u'\U0001F53A',
    'DOWN-POINTING RED TRIANGLE':                               u'\U0001F53B',
    'UP-POINTING SMALL RED TRIANGLE':                           u'\U0001F53C',
    'DOWN-POINTING SMALL RED TRIANGLE':                         u'\U0001F53D',

    # Shadowed geometric shapes:
    # 'LOWER RIGHT SHADOWED WHITE CIRCLE':                        u'\U0001F53E',
    # 'UPPER RIGHT SHADOWED WHITE CIRCLE':                        u'\U0001F53F',

    # Religious symbols:
    # 'CIRCLED CROSS POMMEE':                                     u'\U0001F540',
    # 'CROSS POMMEE WITH HALF-CIRCLE BELOW':                      u'\U0001F541',
    # 'CROSS POMMEE':                                             u'\U0001F542',
    # 'NOTCHED LEFT SEMICIRCLE WITH THREE DOTS':                  u'\U0001F543',
    # 'NOTCHED RIGHT SEMICIRCLE WITH THREE DOTS':                 u'\U0001F544',
    # 'SYMBOL FOR MARKS CHAPTER':                                 u'\U0001F545',
    # 'WHITE LATIN CROSS':                                        u'\U0001F546',
    # 'HEAVY LATIN CROSS':                                        u'\U0001F547',
    # 'CELTIC CROSS':                                             u'\U0001F548',
    # 'OM SYMBOL':                                                u'\U0001F549',
    # 'DOVE OF PEACE':                                            u'\U0001F54A',

    # Clock face symbols:
    'CLOCK FACE ONE OCLOCK':                                    u'\U0001F550',
    'CLOCK FACE TWO OCLOCK':                                    u'\U0001F551',
    'CLOCK FACE THREE OCLOCK':                                  u'\U0001F552',
    'CLOCK FACE FOUR OCLOCK':                                   u'\U0001F553',
    'CLOCK FACE FIVE OCLOCK':                                   u'\U0001F554',
    'CLOCK FACE SIX OCLOCK':                                    u'\U0001F555',
    'CLOCK FACE SEVEN OCLOCK':                                  u'\U0001F556',
    'CLOCK FACE EIGHT OCLOCK':                                  u'\U0001F557',
    'CLOCK FACE NINE OCLOCK':                                   u'\U0001F558',
    'CLOCK FACE TEN OCLOCK':                                    u'\U0001F559',
    'CLOCK FACE ELEVEN OCLOCK':                                 u'\U0001F55A',
    'CLOCK FACE TWELVE OCLOCK':                                 u'\U0001F55B',
    'CLOCK FACE ONE-THIRTY':                                    u'\U0001F55C',
    'CLOCK FACE TWO-THIRTY':                                    u'\U0001F55D',
    'CLOCK FACE THREE-THIRTY':                                  u'\U0001F55E',
    'CLOCK FACE FOUR-THIRTY':                                   u'\U0001F55F',
    'CLOCK FACE FIVE-THIRTY':                                   u'\U0001F560',
    'CLOCK FACE SIX-THIRTY':                                    u'\U0001F561',
    'CLOCK FACE SEVEN-THIRTY':                                  u'\U0001F562',
    'CLOCK FACE EIGHT-THIRTY':                                  u'\U0001F563',
    'CLOCK FACE NINE-THIRTY':                                   u'\U0001F564',
    'CLOCK FACE TEN-THIRTY':                                    u'\U0001F565',
    'CLOCK FACE ELEVEN-THIRTY':                                 u'\U0001F566',
    'CLOCK FACE TWELVE-THIRTY':                                 u'\U0001F567',

    # Communication symbols:
    # 'RIGHT SPEAKER':                                            u'\U0001F568',
    # 'RIGHT SPEAKER WITH ONE SOUND WAVE':                        u'\U0001F569',
    # 'RIGHT SPEAKER WITH THREE SOUND WAVES':                     u'\U0001F56A',
    # 'BULLHORN':                                                 u'\U0001F56B',
    # 'BULLHORN WITH SOUND WAVES':                                u'\U0001F56C',

    # Miscellaneous symbols:
    # 'RINGING BELL':                                             u'\U0001F56D',
    # 'BOOK':                                                     u'\U0001F56E',
    # 'CANDLE':                                                   u'\U0001F56F',
    # 'MANTELPIECE CLOCK':                                        u'\U0001F570',
    # 'BLACK SKULL AND CROSSBONES':                               u'\U0001F571',
    # 'NO PIRACY':                                                u'\U0001F572',
    # 'HOLE':                                                     u'\U0001F573',
    # 'MAN IN BUSINESS SUIT LEVITATING':                          u'\U0001F574',
    # 'SLEUTH OR SPY':                                            u'\U0001F575',
    # 'DARK SUNGLASSES':                                          u'\U0001F576',

    # Animal symbols:
    # 'SPIDER':                                                   u'\U0001F577',
    # 'SPIDER WEB':                                               u'\U0001F578',

    # Game symbol:
    # 'JOYSTICK':                                                 u'\U0001F579',

    # Communication symbols:
    # 'LEFT HAND TELEPHONE RECEIVER':                             u'\U0001F57B',
    # 'TELEPHONE RECEIVER WITH PAGE':                             u'\U0001F57C',
    # 'RIGHT HAND TELEPHONE RECEIVER':                            u'\U0001F57D',
    # 'WHITE TOUCHTONE TELEPHONE':                                u'\U0001F57E',
    # 'BLACK TOUCHTONE TELEPHONE':                                u'\U0001F57F',
    # 'TELEPHONE ON TOP OF MODEM':                                u'\U0001F580',
    # 'CLAMSHELL MOBILE PHONE':                                   u'\U0001F581',
    # 'BACK OF ENVELOPE':                                         u'\U0001F582',
    # 'STAMPED ENVELOPE':                                         u'\U0001F583',
    # 'ENVELOPE WITH LIGHTNING':                                  u'\U0001F584',
    # 'FLYING ENVELOPE':                                          u'\U0001F585',
    # 'PEN OVER STAMPED ENVELOPE':                                u'\U0001F586',
    # 'LINKED PAPERCLIPS':                                        u'\U0001F587',
    # 'BLACK PUSHPIN':                                            u'\U0001F588',
    # 'LOWER LEFT PENCIL':                                        u'\U0001F589',
    # 'LOWER LEFT BALLPOINT PEN':                                 u'\U0001F58A',
    # 'LOWER LEFT FOUNTAIN PEN':                                  u'\U0001F58B',
    # 'LOWER LEFT PAINTBRUSH':                                    u'\U0001F58C',
    # 'LOWER LEFT CRAYON':                                        u'\U0001F58D',

    # Hand symbols:
    # 'LEFT WRITING HAND':                                        u'\U0001F58E',
    # 'TURNED OK HAND SIGN':                                      u'\U0001F58F',
    # 'RAISED HAND WITH FINGERS SPLAYED':                         u'\U0001F590',
    # 'REVERSED RAISED HAND WITH FINGERS SPLAYED':                u'\U0001F591',
    # 'REVERSED THUMBS UP SIGN':                                  u'\U0001F592',
    # 'REVERSED THUMBS DOWN SIGN':                                u'\U0001F593',
    # 'REVERSED VICTORY HAND':                                    u'\U0001F594',
    # 'REVERSED HAND WITH MIDDLE FINGER EXTENDED':                u'\U0001F595',
    # 'RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS':    u'\U0001F596',
    # 'WHITE DOWN POINTING LEFT HAND INDEX':                      u'\U0001F597',
    # 'SIDEWAYS WHITE LEFT POINTING INDEX':                       u'\U0001F598',
    # 'SIDEWAYS WHITE RIGHT POINTING INDEX':                      u'\U0001F599',
    # 'SIDEWAYS BLACK LEFT POINTING INDEX':                       u'\U0001F59A',
    # 'SIDEWAYS BLACK RIGHT POINTING INDEX':                      u'\U0001F59B',
    # 'BLACK LEFT POINTING BACKHAND INDEX':                       u'\U0001F59C',
    # 'BLACK RIGHT POINTING BACKHAND INDEX':                      u'\U0001F59D',
    # 'SIDEWAYS WHITE UP POINTING INDEX':                         u'\U0001F59E',
    # 'SIDEWAYS WHITE DOWN POINTING INDEX':                       u'\U0001F59E',
    # 'SIDEWAYS BLACK UP POINTING INDEX':                         u'\U0001F5A0',
    # 'SIDEWAYS BLACK DOWN POINTING INDEX':                       u'\U0001F5A1',
    # 'BLACK UP POINTING BACKHAND INDEX':                         u'\U0001F5A2',
    # 'BLACK DOWN POINTING BACKHAND INDEX':                       u'\U0001F5A3',

    # Computer symbols:
    # 'DESKTOP COMPUTER':                                         u'\U0001F5A5',
    # 'KEYBOARD AND MOUSE':                                       u'\U0001F5A6',
    # 'THREE NETWORKED COMPUTERS':                                u'\U0001F5A7',
    # 'PRINTER':                                                  u'\U0001F5A8',
    # 'POCKET CALCULATOR':                                        u'\U0001F5A9',
    # 'BLACK HARD SHELL FLOPPY DISK':                             u'\U0001F5AA',
    # 'WHITE HARD SHELL FLOPPY DISK':                             u'\U0001F5AB',
    # 'SOFT SHELL FLOPPY DISK':                                   u'\U0001F5AC',
    # 'TAPE CARTRIDGE':                                           u'\U0001F5AD',
    # 'WIRED KEYBOARD':                                           u'\U0001F5AE',
    # 'ONE BUTTON MOUSE':                                         u'\U0001F5AF',
    # 'TWO BUTTON MOUSE':                                         u'\U0001F5B0',
    # 'THREE BUTTON MOUSE':                                       u'\U0001F5B1',
    # 'TRACKBALL':                                                u'\U0001F5B2',
    # 'OLD PERSONAL COMPUTER':                                    u'\U0001F5B3',
    # 'HARD DISK':                                                u'\U0001F5B4',
    # 'SCREEN':                                                   u'\U0001F5B5',
    # 'PRINTER ICON':                                             u'\U0001F5B6',
    # 'FAX ICON':                                                 u'\U0001F5B7',
    # 'OPTICAL DISC ICON':                                        u'\U0001F5B8',

    # Office symbols:
    # 'DOCUMENT WITH TEXT':                                       u'\U0001F5B9',
    # 'DOCUMENT WITH TEXT AND PICTURE':                           u'\U0001F5BA',
    # 'DOCUMENT WITH PICTURE':                                    u'\U0001F5BB',
    # 'FRAME WITH PICTURE':                                       u'\U0001F5BC',
    # 'FRAME WITH TILES':                                         u'\U0001F5BD',
    # 'FRAME WITH AN X':                                          u'\U0001F5BE',

    # User interface symbols:
    # 'BLACK FOLDER':                                             u'\U0001F5BF',
    # 'FOLDER':                                                   u'\U0001F5C0',
    # 'OPEN FOLDER':                                              u'\U0001F5C1',
    # 'CARD INDEX DIVIDERS':                                      u'\U0001F5C2',
    # 'CARD FILE BOX':                                            u'\U0001F5C3',
    # 'FILE CABINET':                                             u'\U0001F5C4',
    # 'EMPTY NOTE':                                               u'\U0001F5C5',
    # 'EMPTY NOTE PAGE':                                          u'\U0001F5C6',
    # 'EMPTY NOTE PAD':                                           u'\U0001F5C7',
    # 'NOTE':                                                     u'\U0001F5C8',
    # 'NOTE PAGE':                                                u'\U0001F5C9',
    # 'NOTE PAD':                                                 u'\U0001F5CA',
    # 'EMPTY DOCUMENT':                                           u'\U0001F5CB',
    # 'EMPTY PAGE':                                               u'\U0001F5CC',
    # 'EMPTY PAGES':                                              u'\U0001F5CD',
    # 'DOCUMENT':                                                 u'\U0001F5CE',
    # 'PAGE':                                                     u'\U0001F5CF',
    # 'PAGES':                                                    u'\U0001F5D0',
    # 'WASTEBASKET':                                              u'\U0001F5D1',
    # 'SPIRAL NOTE PAD':                                          u'\U0001F5D2',
    # 'SPIRAL CALENDAR PAD':                                      u'\U0001F5D3',
    # 'DESKTOP WINDOW':                                           u'\U0001F5D4',
    # 'MINIMIZE':                                                 u'\U0001F5D5',
    # 'MAXIMIZE':                                                 u'\U0001F5D6',
    # 'OVERLAP':                                                  u'\U0001F5D7',
    # 'CLOCKWISE RIGHT AND LEFT SEMICIRCLE ARROWS':               u'\U0001F5D8',
    # 'CANCELLATION X':                                           u'\U0001F5D9',
    # 'INCREASE FONT SIZE SYMBOL':                                u'\U0001F5DA',
    # 'DECREASE FONT SIZE SYMBOL':                                u'\U0001F5DB',
    # 'COMPRESSION':                                              u'\U0001F5DC',
    # 'OLD KEY':                                                  u'\U0001F5DD',

    # Miscellaneous symbols:
    # 'ROLLED-UP NEWSPAPER':                                      u'\U0001F5DE',
    # 'PAGE WITH CIRCLED TEXT':                                   u'\U0001F5DF',
    # 'STOCK CHART':                                              u'\U0001F5E0',

    # Rating symbols:
    # 'DAGGER KNIFE':                                             u'\U0001F5E1',
    # 'LIPS':                                                     u'\U0001F5E2',
    # 'SPEAKING HEAD IN SILHOUETTE':                              u'\U0001F5E3',

    # Sound symbols:
    # 'THREE RAYS ABOVE':                                         u'\U0001F5E4',
    # 'THREE RAYS BELOW':                                         u'\U0001F5E5',
    # 'THREE RAYS LEFT':                                          u'\U0001F5E6',
    # 'THREE RAYS RIGHT':                                         u'\U0001F5E7',

    # Bubble symbols:
    # 'LEFT SPEECH BUBBLE':                                       u'\U0001F5E8',
    # 'RIGHT SPEECH BUBBLE':                                      u'\U0001F5E9',
    # 'TWO SPEECH BUBBLES':                                       u'\U0001F5EA',
    # 'THREE SPEECH BUBBLES':                                     u'\U0001F5EB',
    # 'LEFT THOUGHT BUBBLE':                                      u'\U0001F5EC',
    # 'RIGHT THOUGHT BUBBLE':                                     u'\U0001F5ED',
    # 'LEFT ANGER BUBBLE':                                        u'\U0001F5EE',
    # 'RIGHT ANGER BUBBLE':                                       u'\U0001F5EF',
    # 'MOOD BUBBLE':                                              u'\U0001F5F0',
    # 'LIGHTNING MOOD BUBBLE':                                    u'\U0001F5F1',
    # 'LIGHTNING MOOD':                                           u'\U0001F5F2',

    # Ballot symbols:
    # 'BALLOT BOX WITH BALLOT':                                   u'\U0001F5F3',
    # 'BALLOT SCRIPT X':                                          u'\U0001F5F4',
    # 'BALLOT BOX WITH SCRIPT X':                                 u'\U0001F5F5',
    # 'BALLOT BOLD SCRIPT X':                                     u'\U0001F5F6',
    # 'BALLOT BOX WITH BOLD SCRIPT X':                            u'\U0001F5F7',
    # 'LIGHT CHECK MARK':                                         u'\U0001F5F8',
    # 'BALLOT BOX WITH BOLD CHECK':                               u'\U0001F5F9',

    # Map symbol:
    # 'WORLD MAP':                                                u'\U0001F5FA',

    # Cultural symbols:
    'MOUNT FUJI':                                               u'\U0001F5FB',
    'TOKYO TOWER':                                              u'\U0001F5FC',
    'STATUE OF LIBERTY':                                        u'\U0001F5FD',
    'SILHOUETTE OF JAPAN':                                      u'\U0001F5FE',
    'MOYAI':                                                    u'\U0001F5FF',
}



def main():
    for key, value in EMOJI.items():
        line = u'{0}  - {1}'.format(value, key)
        print(line)

if __name__ == '__main__':
    main()
